//                                  +++++++++++++++++++++++++++++++
//                                   UNDERSTANDING REFERENCE TYPES
//                                  +++++++++++++++++++++++++++++++
import java.util.Date; 
    // this is automatically generated by java 

public class second {
    public static void main(String[] args){
        Date now = new Date();
            // use Date.util.java and hit enter 
            //MEMORY ALLOCATION IS MUST FOR REFERNCE TYPE  
        System.out.println(now);
    }       // instead of typing this above line type sout and hit Tab and print the current date and time :)
}
 